### ISSUE TITLE
coercing to Unicode: need string or buffer, ContentType found

### ISSUE THREAD

**Issue by li5tun** [romansalin/django-seo2#8]
ERROR:django.request:Internal Server Error: /admin/djangoseo/youlunmetadatamodel/add/
Traceback (most recent call last):
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1407, in changeform_view
    self.log_addition(request, new_object)
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 776, in log_addition
    object_repr=force_text(object),
  File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/django/utils/encoding.py", line 85, in force_text
    s = six.text_type(s)
TypeError: coercing to Unicode: need string or buffer, ContentType found

**Comment by li5tun** [comment]
https://github.com/romansalin/django-seo2/blob/952741849974415edc44bba0200d1c3b48c01fc2/djangoseo/backends.py#L451
I think this one should return a string, instead of `content_type`.

**Comment by romansalin** [comment]
Thank you for the issue, I'm going to fix this within 24 hours.

**Comment by mic159** [comment]
We have hit this error too, the grappelli admin wont load because of it.
It also stops you from printing it in the console.

```python
In [10]: ObjectMetaDataModel.objects.all()
Out[10]: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
... snip ...
TypeError: coercing to Unicode: need string or buffer, ContentType found

In [11]: 

```

**Comment by fzdmd** [comment]
Same problem, is anybody knows how to fix if ?

**Comment by fragmuffin** [comment]
fixed in: https://github.com/romansalin/django-seo2/commit/68d1184064fa3b94dafce93610191cc7fa5a5a04

**Comment by mic159** [comment]
Yeah, looks like this was in PR #13.
@romansalin any chance on getting a release uploaded to pypi?
Its been more than 24 hours :cry:

**Comment by Shivam1904** [comment]
Hey @romansalin ,
Can you please release the new updated patch to pypi as the version downloaded via pip still throws this error.

**Comment by mic159** [comment]
@romansalin please release to pypi!

**Comment by mic159** [comment]
@romansalin bump!

**Comment by fannyhub** [comment]
@romansalin, please release the fix...
